
spring.jpa.properties.hibernate.format_sql=true
# ???? ?
server.tomcat.mbeanregistry.enabled=true
# ?? ??????? ? 500?
server.tomcat.accept-count=500


spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.challenge_summer.bigtraffic=INFO